blogger/config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

blogger/app/models/article.rb
class Article < ActiveRecord::Base
end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save!

    redirect_to article_url(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    Article.find(params[:id]).destroy
    
    redirect_to articles_url
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_url(@article)
  end

end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

blogger/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

blogger/app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

blogger/app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<%= link_to "<< Back to Articles List", articles_path %>
<br>
<%= link_to "delete", article_path(@article), method: :delete, data: { confirm: "Really delete the article?" }%>
<br>
<%= link_to "edit", edit_article_path(@article) %>