MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :update]
  end

  resources :notes, only: :destroy

end

MusicApp/app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_one :band, through: :album, source: :band
  has_many :notes, dependent: :destroy
  enum track_type: [ :regular, :bonus ]
  validates :title, :track_type, :album_id, presence: true
  validates :track_type, inclusion: { in: Track.track_types.keys }
  validates :album, presence: true
  
end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :make_sure_user_is_logged_in

  def new
    @track = Track.new
    @albums = Album.all
    @track.album_id = params[:album_id]
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      flash[:messages] = ["Successfully Created Track!"]
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
  end

  def show
    @track = Track.includes(:notes).find(params[:id])
    @note = Note.new
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      flash[:messages] = ["Succesffully Created Track!"]
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      render :edi
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to bands_url
  end

  private
  def track_params
    params.require(:track).permit(:title, :track_type, :album_id, :lyrics)
  end
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/views/tracks/_form.html.erb
<% if @track.persisted? %>
  <% form_destination = track_url(@track) %>
  <% form_method = "patch" %>
<% else %>
  <% form_destination = tracks_url %>
  <% form_method = "post" %>
<% end %>


<form action="<%= form_destination %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

  <label>Title
    <input type="text" name="track[title]" value="<%= @track.title %>">
  </label>
  <br>

  <label>Album
    <select name="track[album_id]">
      <option></option>
      <% @albums.each do |album| %>
        <option
        value="<%= album.id %>"
        <%= "selected" if album == @track.album %>><%= album.title %></option>
      <% end %>
    </select>
  </label>
  <br>

  <% Track.track_types.keys.each do |track_type| %>
    <label>
      <input
      type="radio"
      name="track[track_type]"
      value="<%= track_type %>"
      <%= "checked" if @track.track_type == track_type %>>
        <%= track_type.upcase %>
    </label>
  <% end %>
  <br>

  <label>Lyrics<br>
    <textarea name="track[lyrics]" rows="50"><%= @track.lyrics %></textarea>
  </label>
  <br>

  <input type="submit" value="submit">
</form>

MusicApp/app/views/tracks/edit.html.erb
<h1>Edit Track</h1>

<%= render "shared/errors" %>
<%= render "form" %>

MusicApp/app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render "shared/errors" %>
<%= render "form" %>

MusicApp/app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<p>
Band: <%= @track.band.name %><br>
Album: <%= @track.album.title %>
</p>
<% if @track.lyrics %>
  <h3>lyrics</h3>
  <pre>
  <%= ugly_lyrics(@track.lyrics) %>
  </pre>
<% end %>
<br>
<%= link_to "edit track", edit_track_url(@track) %>
<br>
<%= render 'notes/form' %>
<br>
<%= render 'notes/note' %>